/* GENERATED by tools/h245/per_gen.py from the MULTIMEDIA-SYSTEM-CONTROL
 * module of ITU-T H.245 (03/2022).  Do not edit; see tools/h245/prune.py for
 * the subset.  Dropped alternatives are counted but have no schema ("0"). */
#include "per.h"

const a_type_t T_SequenceNumber = { A_INT, 0, 1, 1, 0LL, 255LL, 0, 0, 0, 0, "SequenceNumber" };
const a_type_t T_TerminalCapabilitySet_protocolIdentifier = { A_OID, 0, 0, 0, 0LL, 0LL, 0, 0, 0, 0, "TerminalCapabilitySet.protocolIdentifier" };
const a_type_t T_V76Capability_numOfDLCS = { A_INT, 0, 1, 1, 2LL, 8191LL, 0, 0, 0, 0, "V76Capability.numOfDLCS" };
const a_type_t T_V76Capability_n401Capability = { A_INT, 0, 1, 1, 1LL, 4095LL, 0, 0, 0, 0, "V76Capability.n401Capability" };
const a_type_t T_V76Capability_maxWindowSizeCapability = { A_INT, 0, 1, 1, 1LL, 127LL, 0, 0, 0, 0, "V76Capability.maxWindowSizeCapability" };
static const a_member_t M_T_V75Capability[] = {
    { "audioHeader", &T_BOOLEAN, 0 },
};
const a_type_t T_V75Capability = { A_SEQ, 1, 0, 0, 0LL, 0LL, 1, 1, M_T_V75Capability, 0, "V75Capability" };
static const a_member_t M_T_V76Capability[] = {
    { "suspendResumeCapabilitywAddress", &T_BOOLEAN, 0 },
    { "suspendResumeCapabilitywoAddress", &T_BOOLEAN, 0 },
    { "rejCapability", &T_BOOLEAN, 0 },
    { "sREJCapability", &T_BOOLEAN, 0 },
    { "mREJCapability", &T_BOOLEAN, 0 },
    { "crc8bitCapability", &T_BOOLEAN, 0 },
    { "crc16bitCapability", &T_BOOLEAN, 0 },
    { "crc32bitCapability", &T_BOOLEAN, 0 },
    { "uihCapability", &T_BOOLEAN, 0 },
    { "numOfDLCS", &T_V76Capability_numOfDLCS, 0 },
    { "twoOctetAddressFieldCapability", &T_BOOLEAN, 0 },
    { "loopBackTestCapability", &T_BOOLEAN, 0 },
    { "n401Capability", &T_V76Capability_n401Capability, 0 },
    { "maxWindowSizeCapability", &T_V76Capability_maxWindowSizeCapability, 0 },
    { "v75Capability", &T_V75Capability, 0 },
};
const a_type_t T_V76Capability = { A_SEQ, 1, 0, 0, 0LL, 0LL, 15, 15, M_T_V76Capability, 0, "V76Capability" };
static const a_member_t M_T_MultiplexCapability[] = {
    { "nonStandard", 0, 0 },
    { "h222Capability", 0, 0 },
    { "h223Capability", 0, 0 },
    { "v76Capability", &T_V76Capability, 0 },
    { "h2250Capability", 0, 0 },
    { "genericMultiplexCapability", 0, 0 },
};
const a_type_t T_MultiplexCapability = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 4, 6, M_T_MultiplexCapability, 0, "MultiplexCapability" };
const a_type_t T_CapabilityTableEntryNumber = { A_INT, 0, 1, 1, 1LL, 65535LL, 0, 0, 0, 0, "CapabilityTableEntryNumber" };
const a_type_t T_AudioCapability_g711Alaw64k = { A_INT, 0, 1, 1, 1LL, 256LL, 0, 0, 0, 0, "AudioCapability.g711Alaw64k" };
const a_type_t T_AudioCapability_g711Alaw56k = { A_INT, 0, 1, 1, 1LL, 256LL, 0, 0, 0, 0, "AudioCapability.g711Alaw56k" };
const a_type_t T_AudioCapability_g711Ulaw64k = { A_INT, 0, 1, 1, 1LL, 256LL, 0, 0, 0, 0, "AudioCapability.g711Ulaw64k" };
const a_type_t T_AudioCapability_g711Ulaw56k = { A_INT, 0, 1, 1, 1LL, 256LL, 0, 0, 0, 0, "AudioCapability.g711Ulaw56k" };
const a_type_t T_AudioCapability_g722_64k = { A_INT, 0, 1, 1, 1LL, 256LL, 0, 0, 0, 0, "AudioCapability.g722-64k" };
const a_type_t T_AudioCapability_g722_56k = { A_INT, 0, 1, 1, 1LL, 256LL, 0, 0, 0, 0, "AudioCapability.g722-56k" };
const a_type_t T_AudioCapability_g722_48k = { A_INT, 0, 1, 1, 1LL, 256LL, 0, 0, 0, 0, "AudioCapability.g722-48k" };
const a_type_t T_AudioCapability_g7231_maxAl_sduAudioFrames = { A_INT, 0, 1, 1, 1LL, 256LL, 0, 0, 0, 0, "AudioCapability.g7231.maxAl-sduAudioFrames" };
static const a_member_t M_T_AudioCapability_g7231[] = {
    { "maxAl-sduAudioFrames", &T_AudioCapability_g7231_maxAl_sduAudioFrames, 0 },
    { "silenceSuppression", &T_BOOLEAN, 0 },
};
const a_type_t T_AudioCapability_g7231 = { A_SEQ, 0, 0, 0, 0LL, 0LL, 2, 2, M_T_AudioCapability_g7231, 0, "AudioCapability.g7231" };
const a_type_t T_AudioCapability_g728 = { A_INT, 0, 1, 1, 1LL, 256LL, 0, 0, 0, 0, "AudioCapability.g728" };
const a_type_t T_AudioCapability_g729 = { A_INT, 0, 1, 1, 1LL, 256LL, 0, 0, 0, 0, "AudioCapability.g729" };
const a_type_t T_AudioCapability_g729AnnexA = { A_INT, 0, 1, 1, 1LL, 256LL, 0, 0, 0, 0, "AudioCapability.g729AnnexA" };
const a_type_t T_AudioCapability_g729wAnnexB = { A_INT, 0, 1, 1, 1LL, 256LL, 0, 0, 0, 0, "AudioCapability.g729wAnnexB" };
const a_type_t T_AudioCapability_g729AnnexAwAnnexB = { A_INT, 0, 1, 1, 1LL, 256LL, 0, 0, 0, 0, "AudioCapability.g729AnnexAwAnnexB" };
static const a_member_t M_T_AudioCapability[] = {
    { "nonStandard", 0, 0 },
    { "g711Alaw64k", &T_AudioCapability_g711Alaw64k, 0 },
    { "g711Alaw56k", &T_AudioCapability_g711Alaw56k, 0 },
    { "g711Ulaw64k", &T_AudioCapability_g711Ulaw64k, 0 },
    { "g711Ulaw56k", &T_AudioCapability_g711Ulaw56k, 0 },
    { "g722-64k", &T_AudioCapability_g722_64k, 0 },
    { "g722-56k", &T_AudioCapability_g722_56k, 0 },
    { "g722-48k", &T_AudioCapability_g722_48k, 0 },
    { "g7231", &T_AudioCapability_g7231, 0 },
    { "g728", &T_AudioCapability_g728, 0 },
    { "g729", &T_AudioCapability_g729, 0 },
    { "g729AnnexA", &T_AudioCapability_g729AnnexA, 0 },
    { "is11172AudioCapability", 0, 0 },
    { "is13818AudioCapability", 0, 0 },
    { "g729wAnnexB", &T_AudioCapability_g729wAnnexB, 0 },
    { "g729AnnexAwAnnexB", &T_AudioCapability_g729AnnexAwAnnexB, 0 },
    { "g7231AnnexCCapability", 0, 0 },
    { "gsmFullRate", 0, 0 },
    { "gsmHalfRate", 0, 0 },
    { "gsmEnhancedFullRate", 0, 0 },
    { "genericAudioCapability", 0, 0 },
    { "g729Extensions", 0, 0 },
    { "vbd", 0, 0 },
    { "audioTelephonyEvent", 0, 0 },
    { "audioTone", 0, 0 },
    { "extendedAudioCapability", 0, 0 },
};
const a_type_t T_AudioCapability = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 14, 26, M_T_AudioCapability, 0, "AudioCapability" };
const a_type_t T_V42bis_numberOfCodewords = { A_INT, 0, 1, 1, 1LL, 65536LL, 0, 0, 0, 0, "V42bis.numberOfCodewords" };
const a_type_t T_V42bis_maximumStringLength = { A_INT, 0, 1, 1, 1LL, 256LL, 0, 0, 0, 0, "V42bis.maximumStringLength" };
static const a_member_t M_T_V42bis[] = {
    { "numberOfCodewords", &T_V42bis_numberOfCodewords, 0 },
    { "maximumStringLength", &T_V42bis_maximumStringLength, 0 },
};
const a_type_t T_V42bis = { A_SEQ, 1, 0, 0, 0LL, 0LL, 2, 2, M_T_V42bis, 0, "V42bis" };
static const a_member_t M_T_CompressionType[] = {
    { "v42bis", &T_V42bis, 0 },
};
const a_type_t T_CompressionType = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 1, 1, M_T_CompressionType, 0, "CompressionType" };
static const a_member_t M_T_DataProtocolCapability_v76wCompression[] = {
    { "transmitCompression", &T_CompressionType, 0 },
    { "receiveCompression", &T_CompressionType, 0 },
    { "transmitAndReceiveCompression", &T_CompressionType, 0 },
};
const a_type_t T_DataProtocolCapability_v76wCompression = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 3, 3, M_T_DataProtocolCapability_v76wCompression, 0, "DataProtocolCapability.v76wCompression" };
static const a_member_t M_T_DataProtocolCapability[] = {
    { "nonStandard", 0, 0 },
    { "v14buffered", &T_NULL, 0 },
    { "v42lapm", &T_NULL, 0 },
    { "hdlcFrameTunnelling", &T_NULL, 0 },
    { "h310SeparateVCStack", 0, 0 },
    { "h310SingleVCStack", 0, 0 },
    { "transparent", &T_NULL, 0 },
    { "segmentationAndReassembly", &T_NULL, 0 },
    { "hdlcFrameTunnelingwSAR", &T_NULL, 0 },
    { "v120", &T_NULL, 0 },
    { "separateLANStack", 0, 0 },
    { "v76wCompression", &T_DataProtocolCapability_v76wCompression, 0 },
    { "tcp", 0, 0 },
    { "udp", 0, 0 },
    { "sctp", 0, 0 },
    { "udp-dtls-sctp", 0, 0 },
    { "tcp-dtls-sctp", 0, 0 },
    { "sctp-dtls", 0, 0 },
};
const a_type_t T_DataProtocolCapability = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 7, 18, M_T_DataProtocolCapability, 0, "DataProtocolCapability" };
static const a_member_t M_T_DataApplicationCapability_application[] = {
    { "nonStandard", 0, 0 },
    { "t120", &T_DataProtocolCapability, 0 },
    { "dsm-cc", 0, 0 },
    { "userData", &T_DataProtocolCapability, 0 },
    { "t84", 0, 0 },
    { "t434", &T_DataProtocolCapability, 0 },
    { "h224", 0, 0 },
    { "nlpid", 0, 0 },
    { "dsvdControl", &T_NULL, 0 },
    { "h222DataPartitioning", 0, 0 },
    { "t30fax", 0, 0 },
    { "t140", 0, 0 },
    { "t38fax", 0, 0 },
    { "genericDataCapability", 0, 0 },
    { "dataChannel", 0, 0 },
    { "extendedDataCapability", 0, 0 },
};
const a_type_t T_DataApplicationCapability_application = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 10, 16, M_T_DataApplicationCapability_application, 0, "DataApplicationCapability.application" };
const a_type_t T_DataApplicationCapability_maxBitRate = { A_INT, 0, 1, 1, 0LL, 4294967295LL, 0, 0, 0, 0, "DataApplicationCapability.maxBitRate" };
static const a_member_t M_T_DataApplicationCapability[] = {
    { "application", &T_DataApplicationCapability_application, 0 },
    { "maxBitRate", &T_DataApplicationCapability_maxBitRate, 0 },
};
const a_type_t T_DataApplicationCapability = { A_SEQ, 1, 0, 0, 0LL, 0LL, 2, 2, M_T_DataApplicationCapability, 0, "DataApplicationCapability" };
static const a_member_t M_T_Capability[] = {
    { "nonStandard", 0, 0 },
    { "receiveVideoCapability", 0, 0 },
    { "transmitVideoCapability", 0, 0 },
    { "receiveAndTransmitVideoCapability", 0, 0 },
    { "receiveAudioCapability", &T_AudioCapability, 0 },
    { "transmitAudioCapability", &T_AudioCapability, 0 },
    { "receiveAndTransmitAudioCapability", &T_AudioCapability, 0 },
    { "receiveDataApplicationCapability", &T_DataApplicationCapability, 0 },
    { "transmitDataApplicationCapability", &T_DataApplicationCapability, 0 },
    { "receiveAndTransmitDataApplicationCapability", &T_DataApplicationCapability, 0 },
    { "h233EncryptionTransmitCapability", 0, 0 },
    { "h233EncryptionReceiveCapability", 0, 0 },
    { "conferenceCapability", 0, 0 },
    { "h235SecurityCapability", 0, 0 },
    { "maxPendingReplacementFor", 0, 0 },
    { "receiveUserInputCapability", 0, 0 },
    { "transmitUserInputCapability", 0, 0 },
    { "receiveAndTransmitUserInputCapability", 0, 0 },
    { "genericControlCapability", 0, 0 },
    { "receiveMultiplexedStreamCapability", 0, 0 },
    { "transmitMultiplexedStreamCapability", 0, 0 },
    { "receiveAndTransmitMultiplexedStreamCapability", 0, 0 },
    { "receiveRTPAudioTelephonyEventCapability", 0, 0 },
    { "receiveRTPAudioToneCapability", 0, 0 },
    { "depFecCapability", 0, 0 },
    { "multiplePayloadStreamCapability", 0, 0 },
    { "fecCapability", 0, 0 },
    { "redundancyEncodingCap", 0, 0 },
    { "oneOfCapabilities", 0, 0 },
};
const a_type_t T_Capability = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 12, 29, M_T_Capability, 0, "Capability" };
static const a_member_t M_T_CapabilityTableEntry[] = {
    { "capabilityTableEntryNumber", &T_CapabilityTableEntryNumber, 0 },
    { "capability", &T_Capability, 1 },
};
const a_type_t T_CapabilityTableEntry = { A_SEQ, 0, 0, 0, 0LL, 0LL, 2, 2, M_T_CapabilityTableEntry, 0, "CapabilityTableEntry" };
const a_type_t T_TerminalCapabilitySet_capabilityTable = { A_SEQOF, 0, 1, 1, 1LL, 256LL, 0, 0, 0, &T_CapabilityTableEntry, "TerminalCapabilitySet.capabilityTable" };
const a_type_t T_CapabilityDescriptorNumber = { A_INT, 0, 1, 1, 0LL, 255LL, 0, 0, 0, 0, "CapabilityDescriptorNumber" };
const a_type_t T_AlternativeCapabilitySet = { A_SEQOF, 0, 1, 1, 1LL, 256LL, 0, 0, 0, &T_CapabilityTableEntryNumber, "AlternativeCapabilitySet" };
const a_type_t T_CapabilityDescriptor_simultaneousCapabilities = { A_SEQOF, 0, 1, 1, 1LL, 256LL, 0, 0, 0, &T_AlternativeCapabilitySet, "CapabilityDescriptor.simultaneousCapabilities" };
static const a_member_t M_T_CapabilityDescriptor[] = {
    { "capabilityDescriptorNumber", &T_CapabilityDescriptorNumber, 0 },
    { "simultaneousCapabilities", &T_CapabilityDescriptor_simultaneousCapabilities, 1 },
};
const a_type_t T_CapabilityDescriptor = { A_SEQ, 0, 0, 0, 0LL, 0LL, 2, 2, M_T_CapabilityDescriptor, 0, "CapabilityDescriptor" };
const a_type_t T_TerminalCapabilitySet_capabilityDescriptors = { A_SEQOF, 0, 1, 1, 1LL, 256LL, 0, 0, 0, &T_CapabilityDescriptor, "TerminalCapabilitySet.capabilityDescriptors" };
static const a_member_t M_T_TerminalCapabilitySet[] = {
    { "sequenceNumber", &T_SequenceNumber, 0 },
    { "protocolIdentifier", &T_TerminalCapabilitySet_protocolIdentifier, 0 },
    { "multiplexCapability", &T_MultiplexCapability, 1 },
    { "capabilityTable", &T_TerminalCapabilitySet_capabilityTable, 1 },
    { "capabilityDescriptors", &T_TerminalCapabilitySet_capabilityDescriptors, 1 },
    { "genericInformation", 0, 1 },
};
const a_type_t T_TerminalCapabilitySet = { A_SEQ, 1, 0, 0, 0LL, 0LL, 5, 6, M_T_TerminalCapabilitySet, 0, "TerminalCapabilitySet" };
const a_type_t T_LogicalChannelNumber = { A_INT, 0, 1, 1, 1LL, 65535LL, 0, 0, 0, 0, "LogicalChannelNumber" };
const a_type_t T_OpenLogicalChannel_forwardLogicalChannelParameters_portNumber = { A_INT, 0, 1, 1, 0LL, 65535LL, 0, 0, 0, 0, "OpenLogicalChannel.forwardLogicalChannelParameters.portNumber" };
static const a_member_t M_T_DataType[] = {
    { "nonStandard", 0, 0 },
    { "nullData", &T_NULL, 0 },
    { "videoData", 0, 0 },
    { "audioData", &T_AudioCapability, 0 },
    { "data", &T_DataApplicationCapability, 0 },
    { "encryptionData", 0, 0 },
    { "h235Control", 0, 0 },
    { "h235Media", 0, 0 },
    { "multiplexedStream", 0, 0 },
    { "redundancyEncoding", 0, 0 },
    { "multiplePayloadStream", 0, 0 },
    { "depFec", 0, 0 },
    { "fec", 0, 0 },
};
const a_type_t T_DataType = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 6, 13, M_T_DataType, 0, "DataType" };
static const a_member_t M_T_CRCLength[] = {
    { "crc8bit", &T_NULL, 0 },
    { "crc16bit", &T_NULL, 0 },
    { "crc32bit", &T_NULL, 0 },
};
const a_type_t T_CRCLength = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 3, 3, M_T_CRCLength, 0, "CRCLength" };
const a_type_t T_V76HDLCParameters_n401 = { A_INT, 0, 1, 1, 1LL, 4095LL, 0, 0, 0, 0, "V76HDLCParameters.n401" };
static const a_member_t M_T_V76HDLCParameters[] = {
    { "crcLength", &T_CRCLength, 0 },
    { "n401", &T_V76HDLCParameters_n401, 0 },
    { "loopbackTestProcedure", &T_BOOLEAN, 0 },
};
const a_type_t T_V76HDLCParameters = { A_SEQ, 1, 0, 0, 0LL, 0LL, 3, 3, M_T_V76HDLCParameters, 0, "V76HDLCParameters" };
static const a_member_t M_T_V76LogicalChannelParameters_suspendResume[] = {
    { "noSuspendResume", &T_NULL, 0 },
    { "suspendResumewAddress", &T_NULL, 0 },
    { "suspendResumewoAddress", &T_NULL, 0 },
};
const a_type_t T_V76LogicalChannelParameters_suspendResume = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 3, 3, M_T_V76LogicalChannelParameters_suspendResume, 0, "V76LogicalChannelParameters.suspendResume" };
const a_type_t T_V76LogicalChannelParameters_mode_eRM_windowSize = { A_INT, 0, 1, 1, 1LL, 127LL, 0, 0, 0, 0, "V76LogicalChannelParameters.mode.eRM.windowSize" };
static const a_member_t M_T_V76LogicalChannelParameters_mode_eRM_recovery[] = {
    { "rej", &T_NULL, 0 },
    { "sREJ", &T_NULL, 0 },
    { "mSREJ", &T_NULL, 0 },
};
const a_type_t T_V76LogicalChannelParameters_mode_eRM_recovery = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 3, 3, M_T_V76LogicalChannelParameters_mode_eRM_recovery, 0, "V76LogicalChannelParameters.mode.eRM.recovery" };
static const a_member_t M_T_V76LogicalChannelParameters_mode_eRM[] = {
    { "windowSize", &T_V76LogicalChannelParameters_mode_eRM_windowSize, 0 },
    { "recovery", &T_V76LogicalChannelParameters_mode_eRM_recovery, 0 },
};
const a_type_t T_V76LogicalChannelParameters_mode_eRM = { A_SEQ, 1, 0, 0, 0LL, 0LL, 2, 2, M_T_V76LogicalChannelParameters_mode_eRM, 0, "V76LogicalChannelParameters.mode.eRM" };
static const a_member_t M_T_V76LogicalChannelParameters_mode[] = {
    { "eRM", &T_V76LogicalChannelParameters_mode_eRM, 0 },
    { "uNERM", &T_NULL, 0 },
};
const a_type_t T_V76LogicalChannelParameters_mode = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 2, 2, M_T_V76LogicalChannelParameters_mode, 0, "V76LogicalChannelParameters.mode" };
static const a_member_t M_T_V75Parameters[] = {
    { "audioHeaderPresent", &T_BOOLEAN, 0 },
};
const a_type_t T_V75Parameters = { A_SEQ, 1, 0, 0, 0LL, 0LL, 1, 1, M_T_V75Parameters, 0, "V75Parameters" };
static const a_member_t M_T_V76LogicalChannelParameters[] = {
    { "hdlcParameters", &T_V76HDLCParameters, 0 },
    { "suspendResume", &T_V76LogicalChannelParameters_suspendResume, 0 },
    { "uIH", &T_BOOLEAN, 0 },
    { "mode", &T_V76LogicalChannelParameters_mode, 0 },
    { "v75Parameters", &T_V75Parameters, 0 },
};
const a_type_t T_V76LogicalChannelParameters = { A_SEQ, 1, 0, 0, 0LL, 0LL, 5, 5, M_T_V76LogicalChannelParameters, 0, "V76LogicalChannelParameters" };
static const a_member_t M_T_OpenLogicalChannel_forwardLogicalChannelParameters_multiplexParameters[] = {
    { "h222LogicalChannelParameters", 0, 0 },
    { "h223LogicalChannelParameters", 0, 0 },
    { "v76LogicalChannelParameters", &T_V76LogicalChannelParameters, 0 },
    { "h2250LogicalChannelParameters", 0, 0 },
    { "none", 0, 0 },
};
const a_type_t T_OpenLogicalChannel_forwardLogicalChannelParameters_multiplexParameters = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 3, 5, M_T_OpenLogicalChannel_forwardLogicalChannelParameters_multiplexParameters, 0, "OpenLogicalChannel.forwardLogicalChannelParameters.multiplexParameters" };
static const a_member_t M_T_OpenLogicalChannel_forwardLogicalChannelParameters[] = {
    { "portNumber", &T_OpenLogicalChannel_forwardLogicalChannelParameters_portNumber, 1 },
    { "dataType", &T_DataType, 0 },
    { "multiplexParameters", &T_OpenLogicalChannel_forwardLogicalChannelParameters_multiplexParameters, 0 },
    { "forwardLogicalChannelDependency", &T_LogicalChannelNumber, 1 },
    { "replacementFor", &T_LogicalChannelNumber, 1 },
};
const a_type_t T_OpenLogicalChannel_forwardLogicalChannelParameters = { A_SEQ, 1, 0, 0, 0LL, 0LL, 3, 5, M_T_OpenLogicalChannel_forwardLogicalChannelParameters, 0, "OpenLogicalChannel.forwardLogicalChannelParameters" };
static const a_member_t M_T_OpenLogicalChannel_reverseLogicalChannelParameters_multiplexParameters[] = {
    { "h223LogicalChannelParameters", 0, 0 },
    { "v76LogicalChannelParameters", &T_V76LogicalChannelParameters, 0 },
    { "h2250LogicalChannelParameters", 0, 0 },
};
const a_type_t T_OpenLogicalChannel_reverseLogicalChannelParameters_multiplexParameters = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 2, 3, M_T_OpenLogicalChannel_reverseLogicalChannelParameters_multiplexParameters, 0, "OpenLogicalChannel.reverseLogicalChannelParameters.multiplexParameters" };
static const a_member_t M_T_OpenLogicalChannel_reverseLogicalChannelParameters[] = {
    { "dataType", &T_DataType, 0 },
    { "multiplexParameters", &T_OpenLogicalChannel_reverseLogicalChannelParameters_multiplexParameters, 1 },
    { "reverseLogicalChannelDependency", &T_LogicalChannelNumber, 1 },
    { "replacementFor", &T_LogicalChannelNumber, 1 },
};
const a_type_t T_OpenLogicalChannel_reverseLogicalChannelParameters = { A_SEQ, 1, 0, 0, 0LL, 0LL, 2, 4, M_T_OpenLogicalChannel_reverseLogicalChannelParameters, 0, "OpenLogicalChannel.reverseLogicalChannelParameters" };
static const a_member_t M_T_OpenLogicalChannel[] = {
    { "forwardLogicalChannelNumber", &T_LogicalChannelNumber, 0 },
    { "forwardLogicalChannelParameters", &T_OpenLogicalChannel_forwardLogicalChannelParameters, 0 },
    { "reverseLogicalChannelParameters", &T_OpenLogicalChannel_reverseLogicalChannelParameters, 1 },
    { "separateStack", 0, 1 },
    { "encryptionSync", 0, 1 },
    { "genericInformation", 0, 1 },
};
const a_type_t T_OpenLogicalChannel = { A_SEQ, 1, 0, 0, 0LL, 0LL, 3, 6, M_T_OpenLogicalChannel, 0, "OpenLogicalChannel" };
static const a_member_t M_T_CloseLogicalChannel_source[] = {
    { "user", &T_NULL, 0 },
    { "lcse", &T_NULL, 0 },
};
const a_type_t T_CloseLogicalChannel_source = { A_CHOICE, 0, 0, 0, 0LL, 0LL, 2, 2, M_T_CloseLogicalChannel_source, 0, "CloseLogicalChannel.source" };
const a_type_t T_CloseLogicalChannel_reason_networkErrorCode = { A_INT, 0, 1, 1, 0LL, 255LL, 0, 0, 0, 0, "CloseLogicalChannel.reason.networkErrorCode" };
static const a_member_t M_T_CloseLogicalChannel_reason[] = {
    { "unknown", &T_NULL, 0 },
    { "reopen", &T_NULL, 0 },
    { "reservationFailure", &T_NULL, 0 },
    { "networkErrorCode", &T_CloseLogicalChannel_reason_networkErrorCode, 0 },
};
const a_type_t T_CloseLogicalChannel_reason = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 3, 4, M_T_CloseLogicalChannel_reason, 0, "CloseLogicalChannel.reason" };
static const a_member_t M_T_CloseLogicalChannel[] = {
    { "forwardLogicalChannelNumber", &T_LogicalChannelNumber, 0 },
    { "source", &T_CloseLogicalChannel_source, 0 },
    { "reason", &T_CloseLogicalChannel_reason, 1 },
};
const a_type_t T_CloseLogicalChannel = { A_SEQ, 1, 0, 0, 0LL, 0LL, 2, 3, M_T_CloseLogicalChannel, 0, "CloseLogicalChannel" };
static const a_member_t M_T_AudioMode_g7231[] = {
    { "noSilenceSuppressionLowRate", &T_NULL, 0 },
    { "noSilenceSuppressionHighRate", &T_NULL, 0 },
    { "silenceSuppressionLowRate", &T_NULL, 0 },
    { "silenceSuppressionHighRate", &T_NULL, 0 },
};
const a_type_t T_AudioMode_g7231 = { A_CHOICE, 0, 0, 0, 0LL, 0LL, 4, 4, M_T_AudioMode_g7231, 0, "AudioMode.g7231" };
const a_type_t T_AudioMode_g729wAnnexB = { A_INT, 0, 1, 1, 1LL, 256LL, 0, 0, 0, 0, "AudioMode.g729wAnnexB" };
const a_type_t T_AudioMode_g729AnnexAwAnnexB = { A_INT, 0, 1, 1, 1LL, 256LL, 0, 0, 0, 0, "AudioMode.g729AnnexAwAnnexB" };
static const a_member_t M_T_AudioMode[] = {
    { "nonStandard", 0, 0 },
    { "g711Alaw64k", &T_NULL, 0 },
    { "g711Alaw56k", &T_NULL, 0 },
    { "g711Ulaw64k", &T_NULL, 0 },
    { "g711Ulaw56k", &T_NULL, 0 },
    { "g722-64k", &T_NULL, 0 },
    { "g722-56k", &T_NULL, 0 },
    { "g722-48k", &T_NULL, 0 },
    { "g728", &T_NULL, 0 },
    { "g729", &T_NULL, 0 },
    { "g729AnnexA", &T_NULL, 0 },
    { "g7231", &T_AudioMode_g7231, 0 },
    { "is11172AudioMode", 0, 0 },
    { "is13818AudioMode", 0, 0 },
    { "g729wAnnexB", &T_AudioMode_g729wAnnexB, 0 },
    { "g729AnnexAwAnnexB", &T_AudioMode_g729AnnexAwAnnexB, 0 },
    { "g7231AnnexCMode", 0, 0 },
    { "gsmFullRate", 0, 0 },
    { "gsmHalfRate", 0, 0 },
    { "gsmEnhancedFullRate", 0, 0 },
    { "genericAudioMode", 0, 0 },
    { "g729Extensions", 0, 0 },
    { "vbd", 0, 0 },
};
const a_type_t T_AudioMode = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 14, 23, M_T_AudioMode, 0, "AudioMode" };
static const a_member_t M_T_DataMode_application[] = {
    { "nonStandard", 0, 0 },
    { "t120", &T_DataProtocolCapability, 0 },
    { "dsm-cc", 0, 0 },
    { "userData", &T_DataProtocolCapability, 0 },
    { "t84", 0, 0 },
    { "t434", &T_DataProtocolCapability, 0 },
    { "h224", 0, 0 },
    { "nlpid", 0, 0 },
    { "dsvdControl", &T_NULL, 0 },
    { "h222DataPartitioning", 0, 0 },
    { "t30fax", 0, 0 },
    { "t140", 0, 0 },
    { "t38fax", 0, 0 },
    { "genericDataMode", 0, 0 },
    { "dataChannel", 0, 0 },
};
const a_type_t T_DataMode_application = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 10, 15, M_T_DataMode_application, 0, "DataMode.application" };
const a_type_t T_DataMode_bitRate = { A_INT, 0, 1, 1, 0LL, 4294967295LL, 0, 0, 0, 0, "DataMode.bitRate" };
static const a_member_t M_T_DataMode[] = {
    { "application", &T_DataMode_application, 0 },
    { "bitRate", &T_DataMode_bitRate, 0 },
};
const a_type_t T_DataMode = { A_SEQ, 1, 0, 0, 0LL, 0LL, 2, 2, M_T_DataMode, 0, "DataMode" };
static const a_member_t M_T_ModeElementType[] = {
    { "nonStandard", 0, 0 },
    { "videoMode", 0, 0 },
    { "audioMode", &T_AudioMode, 0 },
    { "dataMode", &T_DataMode, 0 },
    { "encryptionMode", 0, 0 },
    { "h235Mode", 0, 0 },
    { "multiplexedStreamMode", 0, 0 },
    { "redundancyEncodingDTMode", 0, 0 },
    { "multiplePayloadStreamMode", 0, 0 },
    { "depFecMode", 0, 0 },
    { "fecMode", 0, 0 },
};
const a_type_t T_ModeElementType = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 5, 11, M_T_ModeElementType, 0, "ModeElementType" };
static const a_member_t M_T_V76ModeParameters[] = {
    { "suspendResumewAddress", &T_NULL, 0 },
    { "suspendResumewoAddress", &T_NULL, 0 },
};
const a_type_t T_V76ModeParameters = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 2, 2, M_T_V76ModeParameters, 0, "V76ModeParameters" };
static const a_member_t M_T_ModeElement[] = {
    { "type", &T_ModeElementType, 0 },
    { "h223ModeParameters", 0, 1 },
    { "v76ModeParameters", &T_V76ModeParameters, 1 },
    { "h2250ModeParameters", 0, 1 },
    { "genericModeParameters", 0, 1 },
    { "multiplexedStreamModeParameters", 0, 1 },
    { "logicalChannelNumber", &T_LogicalChannelNumber, 1 },
};
const a_type_t T_ModeElement = { A_SEQ, 1, 0, 0, 0LL, 0LL, 2, 7, M_T_ModeElement, 0, "ModeElement" };
const a_type_t T_ModeDescription = { A_SEQOF, 0, 1, 1, 1LL, 256LL, 0, 0, 0, &T_ModeElement, "ModeDescription" };
const a_type_t T_RequestMode_requestedModes = { A_SEQOF, 0, 1, 1, 1LL, 256LL, 0, 0, 0, &T_ModeDescription, "RequestMode.requestedModes" };
static const a_member_t M_T_RequestMode[] = {
    { "sequenceNumber", &T_SequenceNumber, 0 },
    { "requestedModes", &T_RequestMode_requestedModes, 0 },
};
const a_type_t T_RequestMode = { A_SEQ, 1, 0, 0, 0LL, 0LL, 2, 2, M_T_RequestMode, 0, "RequestMode" };
static const a_member_t M_T_RequestMessage[] = {
    { "nonStandard", 0, 0 },
    { "masterSlaveDetermination", 0, 0 },
    { "terminalCapabilitySet", &T_TerminalCapabilitySet, 0 },
    { "openLogicalChannel", &T_OpenLogicalChannel, 0 },
    { "closeLogicalChannel", &T_CloseLogicalChannel, 0 },
    { "requestChannelClose", 0, 0 },
    { "multiplexEntrySend", 0, 0 },
    { "requestMultiplexEntry", 0, 0 },
    { "requestMode", &T_RequestMode, 0 },
    { "roundTripDelayRequest", 0, 0 },
    { "maintenanceLoopRequest", 0, 0 },
    { "communicationModeRequest", 0, 0 },
    { "conferenceRequest", 0, 0 },
    { "multilinkRequest", 0, 0 },
    { "logicalChannelRateRequest", 0, 0 },
    { "genericRequest", 0, 0 },
};
const a_type_t T_RequestMessage = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 11, 16, M_T_RequestMessage, 0, "RequestMessage" };
static const a_member_t M_T_TerminalCapabilitySetAck[] = {
    { "sequenceNumber", &T_SequenceNumber, 0 },
    { "genericInformation", 0, 1 },
};
const a_type_t T_TerminalCapabilitySetAck = { A_SEQ, 1, 0, 0, 0LL, 0LL, 1, 2, M_T_TerminalCapabilitySetAck, 0, "TerminalCapabilitySetAck" };
static const a_member_t M_T_TerminalCapabilitySetReject_cause_tableEntryCapacityExceeded[] = {
    { "highestEntryNumberProcessed", &T_CapabilityTableEntryNumber, 0 },
    { "noneProcessed", &T_NULL, 0 },
};
const a_type_t T_TerminalCapabilitySetReject_cause_tableEntryCapacityExceeded = { A_CHOICE, 0, 0, 0, 0LL, 0LL, 2, 2, M_T_TerminalCapabilitySetReject_cause_tableEntryCapacityExceeded, 0, "TerminalCapabilitySetReject.cause.tableEntryCapacityExceeded" };
static const a_member_t M_T_TerminalCapabilitySetReject_cause[] = {
    { "unspecified", &T_NULL, 0 },
    { "undefinedTableEntryUsed", &T_NULL, 0 },
    { "descriptorCapacityExceeded", &T_NULL, 0 },
    { "tableEntryCapacityExceeded", &T_TerminalCapabilitySetReject_cause_tableEntryCapacityExceeded, 0 },
};
const a_type_t T_TerminalCapabilitySetReject_cause = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 4, 4, M_T_TerminalCapabilitySetReject_cause, 0, "TerminalCapabilitySetReject.cause" };
static const a_member_t M_T_TerminalCapabilitySetReject[] = {
    { "sequenceNumber", &T_SequenceNumber, 0 },
    { "cause", &T_TerminalCapabilitySetReject_cause, 0 },
    { "genericInformation", 0, 1 },
};
const a_type_t T_TerminalCapabilitySetReject = { A_SEQ, 1, 0, 0, 0LL, 0LL, 2, 3, M_T_TerminalCapabilitySetReject, 0, "TerminalCapabilitySetReject" };
const a_type_t T_OpenLogicalChannelAck_reverseLogicalChannelParameters_portNumber = { A_INT, 0, 1, 1, 0LL, 65535LL, 0, 0, 0, 0, "OpenLogicalChannelAck.reverseLogicalChannelParameters.portNumber" };
static const a_member_t M_T_OpenLogicalChannelAck_reverseLogicalChannelParameters[] = {
    { "reverseLogicalChannelNumber", &T_LogicalChannelNumber, 0 },
    { "portNumber", &T_OpenLogicalChannelAck_reverseLogicalChannelParameters_portNumber, 1 },
    { "multiplexParameters", 0, 1 },
    { "replacementFor", &T_LogicalChannelNumber, 1 },
};
const a_type_t T_OpenLogicalChannelAck_reverseLogicalChannelParameters = { A_SEQ, 1, 0, 0, 0LL, 0LL, 3, 4, M_T_OpenLogicalChannelAck_reverseLogicalChannelParameters, 0, "OpenLogicalChannelAck.reverseLogicalChannelParameters" };
static const a_member_t M_T_OpenLogicalChannelAck[] = {
    { "forwardLogicalChannelNumber", &T_LogicalChannelNumber, 0 },
    { "reverseLogicalChannelParameters", &T_OpenLogicalChannelAck_reverseLogicalChannelParameters, 1 },
    { "separateStack", 0, 1 },
    { "forwardMultiplexAckParameters", 0, 1 },
    { "encryptionSync", 0, 1 },
    { "genericInformation", 0, 1 },
    { "dtlsSecurityCapability", 0, 1 },
};
const a_type_t T_OpenLogicalChannelAck = { A_SEQ, 1, 0, 0, 0LL, 0LL, 2, 7, M_T_OpenLogicalChannelAck, 0, "OpenLogicalChannelAck" };
static const a_member_t M_T_OpenLogicalChannelReject_cause[] = {
    { "unspecified", &T_NULL, 0 },
    { "unsuitableReverseParameters", &T_NULL, 0 },
    { "dataTypeNotSupported", &T_NULL, 0 },
    { "dataTypeNotAvailable", &T_NULL, 0 },
    { "unknownDataType", &T_NULL, 0 },
    { "dataTypeALCombinationNotSupported", &T_NULL, 0 },
    { "multicastChannelNotAllowed", &T_NULL, 0 },
    { "insufficientBandwidth", &T_NULL, 0 },
    { "separateStackEstablishmentFailed", &T_NULL, 0 },
    { "invalidSessionID", &T_NULL, 0 },
    { "masterSlaveConflict", &T_NULL, 0 },
    { "waitForCommunicationMode", &T_NULL, 0 },
    { "invalidDependentChannel", &T_NULL, 0 },
    { "replacementForRejected", &T_NULL, 0 },
    { "securityDenied", &T_NULL, 0 },
    { "qoSControlNotSupported", &T_NULL, 0 },
};
const a_type_t T_OpenLogicalChannelReject_cause = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 6, 16, M_T_OpenLogicalChannelReject_cause, 0, "OpenLogicalChannelReject.cause" };
static const a_member_t M_T_OpenLogicalChannelReject[] = {
    { "forwardLogicalChannelNumber", &T_LogicalChannelNumber, 0 },
    { "cause", &T_OpenLogicalChannelReject_cause, 0 },
    { "genericInformation", 0, 1 },
};
const a_type_t T_OpenLogicalChannelReject = { A_SEQ, 1, 0, 0, 0LL, 0LL, 2, 3, M_T_OpenLogicalChannelReject, 0, "OpenLogicalChannelReject" };
static const a_member_t M_T_CloseLogicalChannelAck[] = {
    { "forwardLogicalChannelNumber", &T_LogicalChannelNumber, 0 },
};
const a_type_t T_CloseLogicalChannelAck = { A_SEQ, 1, 0, 0, 0LL, 0LL, 1, 1, M_T_CloseLogicalChannelAck, 0, "CloseLogicalChannelAck" };
static const a_member_t M_T_RequestModeAck_response[] = {
    { "willTransmitMostPreferredMode", &T_NULL, 0 },
    { "willTransmitLessPreferredMode", &T_NULL, 0 },
};
const a_type_t T_RequestModeAck_response = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 2, 2, M_T_RequestModeAck_response, 0, "RequestModeAck.response" };
static const a_member_t M_T_RequestModeAck[] = {
    { "sequenceNumber", &T_SequenceNumber, 0 },
    { "response", &T_RequestModeAck_response, 0 },
};
const a_type_t T_RequestModeAck = { A_SEQ, 1, 0, 0, 0LL, 0LL, 2, 2, M_T_RequestModeAck, 0, "RequestModeAck" };
static const a_member_t M_T_RequestModeReject_cause[] = {
    { "modeUnavailable", &T_NULL, 0 },
    { "multipointConstraint", &T_NULL, 0 },
    { "requestDenied", &T_NULL, 0 },
};
const a_type_t T_RequestModeReject_cause = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 3, 3, M_T_RequestModeReject_cause, 0, "RequestModeReject.cause" };
static const a_member_t M_T_RequestModeReject[] = {
    { "sequenceNumber", &T_SequenceNumber, 0 },
    { "cause", &T_RequestModeReject_cause, 0 },
};
const a_type_t T_RequestModeReject = { A_SEQ, 1, 0, 0, 0LL, 0LL, 2, 2, M_T_RequestModeReject, 0, "RequestModeReject" };
static const a_member_t M_T_ResponseMessage[] = {
    { "nonStandard", 0, 0 },
    { "masterSlaveDeterminationAck", 0, 0 },
    { "masterSlaveDeterminationReject", 0, 0 },
    { "terminalCapabilitySetAck", &T_TerminalCapabilitySetAck, 0 },
    { "terminalCapabilitySetReject", &T_TerminalCapabilitySetReject, 0 },
    { "openLogicalChannelAck", &T_OpenLogicalChannelAck, 0 },
    { "openLogicalChannelReject", &T_OpenLogicalChannelReject, 0 },
    { "closeLogicalChannelAck", &T_CloseLogicalChannelAck, 0 },
    { "requestChannelCloseAck", 0, 0 },
    { "requestChannelCloseReject", 0, 0 },
    { "multiplexEntrySendAck", 0, 0 },
    { "multiplexEntrySendReject", 0, 0 },
    { "requestMultiplexEntryAck", 0, 0 },
    { "requestMultiplexEntryReject", 0, 0 },
    { "requestModeAck", &T_RequestModeAck, 0 },
    { "requestModeReject", &T_RequestModeReject, 0 },
    { "roundTripDelayResponse", 0, 0 },
    { "maintenanceLoopAck", 0, 0 },
    { "maintenanceLoopReject", 0, 0 },
    { "communicationModeResponse", 0, 0 },
    { "conferenceResponse", 0, 0 },
    { "multilinkResponse", 0, 0 },
    { "logicalChannelRateAcknowledge", 0, 0 },
    { "logicalChannelRateReject", 0, 0 },
    { "genericResponse", 0, 0 },
};
const a_type_t T_ResponseMessage = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 19, 25, M_T_ResponseMessage, 0, "ResponseMessage" };
static const a_member_t M_T_EndSessionCommand_gstnOptions[] = {
    { "telephonyMode", &T_NULL, 0 },
    { "v8bis", &T_NULL, 0 },
    { "v34DSVD", &T_NULL, 0 },
    { "v34DuplexFAX", &T_NULL, 0 },
    { "v34H324", &T_NULL, 0 },
};
const a_type_t T_EndSessionCommand_gstnOptions = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 5, 5, M_T_EndSessionCommand_gstnOptions, 0, "EndSessionCommand.gstnOptions" };
static const a_member_t M_T_EndSessionCommand[] = {
    { "nonStandard", 0, 0 },
    { "disconnect", &T_NULL, 0 },
    { "gstnOptions", &T_EndSessionCommand_gstnOptions, 0 },
    { "isdnOptions", 0, 0 },
    { "genericInformation", 0, 0 },
};
const a_type_t T_EndSessionCommand = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 3, 5, M_T_EndSessionCommand, 0, "EndSessionCommand" };
static const a_member_t M_T_CommandMessage[] = {
    { "nonStandard", 0, 0 },
    { "maintenanceLoopOffCommand", 0, 0 },
    { "sendTerminalCapabilitySet", 0, 0 },
    { "encryptionCommand", 0, 0 },
    { "flowControlCommand", 0, 0 },
    { "endSessionCommand", &T_EndSessionCommand, 0 },
    { "miscellaneousCommand", 0, 0 },
    { "communicationModeCommand", 0, 0 },
    { "conferenceCommand", 0, 0 },
    { "h223MultiplexReconfiguration", 0, 0 },
    { "newATMVCCommand", 0, 0 },
    { "mobileMultilinkReconfigurationCommand", 0, 0 },
    { "genericCommand", 0, 0 },
};
const a_type_t T_CommandMessage = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 7, 13, M_T_CommandMessage, 0, "CommandMessage" };
static const a_member_t M_T_MultimediaSystemControlMessage[] = {
    { "request", &T_RequestMessage, 0 },
    { "response", &T_ResponseMessage, 0 },
    { "command", &T_CommandMessage, 0 },
    { "indication", 0, 0 },
};
const a_type_t T_MultimediaSystemControlMessage = { A_CHOICE, 1, 0, 0, 0LL, 0LL, 4, 4, M_T_MultimediaSystemControlMessage, 0, "MultimediaSystemControlMessage" };

const a_named_t h245_types[] = {
    { "AlternativeCapabilitySet", &T_AlternativeCapabilitySet },
    { "AudioCapability", &T_AudioCapability },
    { "AudioMode", &T_AudioMode },
    { "CRCLength", &T_CRCLength },
    { "Capability", &T_Capability },
    { "CapabilityDescriptor", &T_CapabilityDescriptor },
    { "CapabilityDescriptorNumber", &T_CapabilityDescriptorNumber },
    { "CapabilityTableEntry", &T_CapabilityTableEntry },
    { "CapabilityTableEntryNumber", &T_CapabilityTableEntryNumber },
    { "CloseLogicalChannel", &T_CloseLogicalChannel },
    { "CloseLogicalChannelAck", &T_CloseLogicalChannelAck },
    { "CommandMessage", &T_CommandMessage },
    { "CompressionType", &T_CompressionType },
    { "DataApplicationCapability", &T_DataApplicationCapability },
    { "DataMode", &T_DataMode },
    { "DataProtocolCapability", &T_DataProtocolCapability },
    { "DataType", &T_DataType },
    { "EndSessionCommand", &T_EndSessionCommand },
    { "LogicalChannelNumber", &T_LogicalChannelNumber },
    { "ModeDescription", &T_ModeDescription },
    { "ModeElement", &T_ModeElement },
    { "ModeElementType", &T_ModeElementType },
    { "MultimediaSystemControlMessage", &T_MultimediaSystemControlMessage },
    { "MultiplexCapability", &T_MultiplexCapability },
    { "OpenLogicalChannel", &T_OpenLogicalChannel },
    { "OpenLogicalChannelAck", &T_OpenLogicalChannelAck },
    { "OpenLogicalChannelReject", &T_OpenLogicalChannelReject },
    { "RequestMessage", &T_RequestMessage },
    { "RequestMode", &T_RequestMode },
    { "RequestModeAck", &T_RequestModeAck },
    { "RequestModeReject", &T_RequestModeReject },
    { "ResponseMessage", &T_ResponseMessage },
    { "SequenceNumber", &T_SequenceNumber },
    { "TerminalCapabilitySet", &T_TerminalCapabilitySet },
    { "TerminalCapabilitySetAck", &T_TerminalCapabilitySetAck },
    { "TerminalCapabilitySetReject", &T_TerminalCapabilitySetReject },
    { "V42bis", &T_V42bis },
    { "V75Capability", &T_V75Capability },
    { "V75Parameters", &T_V75Parameters },
    { "V76Capability", &T_V76Capability },
    { "V76HDLCParameters", &T_V76HDLCParameters },
    { "V76LogicalChannelParameters", &T_V76LogicalChannelParameters },
    { "V76ModeParameters", &T_V76ModeParameters },
    { 0, 0 }
};
