"""Reference V.32bis building blocks."""

from .coding import (
    SUPPORTED_BIT_RATES,
    bits_per_symbol,
    encode_symbol_bits,
    differential_encode,
    convolution_encode,
    EncoderState,
    EncodedSymbol,
)
from .constellation import symbol_to_point
from .rate_signal import (
    RATE_14400,
    RATE_12000,
    RATE_9600,
    RATE_7200,
    RATE_4800,
    SUPPORTED_RATE_MASK,
    e_sequence_bits,
    encode_rate_sequence_bits,
    list_from_rate_mask,
    rate_mask_from_list,
    rate_signal_bits,
)
from .scrambler import Descrambler, Scrambler, scrambler_tap
from .negotiation import (
    decode_e_rate,
    decode_rate_mask,
    detect_repeated_rate_signal,
    detect_s_sequence,
    highest_common_rate,
    negotiate_renegotiation_rate,
    negotiate_startup_rate,
    validate_e_sequence_bits,
    validate_rate_signal_bits,
)
from .receiver import DetectedEvent, ReceiverStats, V32bisLogicalReceiver
from .spec_policy import (
    NORMAL_STARTUP_SCRAMBLER_RESET_AFTER_E,
    POST_E_INITIAL_CONVOLUTION_STATE,
    RENEGOTIATION_INITIAL_SCRAMBLER_REGISTER,
    TRN_INITIAL_SCRAMBLER_REGISTER,
    startup_diff_state_from_final_trn_symbol,
    startup_scrambler_register_from_trn,
)
from .rx_frontend import (
    CarrierSearchResult,
    JointSearchResult,
    RecoveredSymbol,
    TimingSearchResult,
    ideal_symbol_samples,
    matched_filter,
    nearest_symbol_label,
    passband_to_baseband,
    recover_symbols_with_frontend,
    recover_symbols_ideal,
    recover_symbols_with_timing_offset,
    search_carrier_frequency,
    search_timing_and_carrier,
    search_symbol_timing,
    symbol_error_metric,
)
from .stream import (
    ObservableSymbol,
    flatten_startup_trace,
    impair_stream,
    impair_stream_burst,
    impair_stream_insert,
    impair_stream_q_neighbor,
    impair_stream_random,
)
from .startup import generate_answer_startup_trace, generate_call_startup_trace
from .simulator import simulate_startup
from .tx import TransmittedSymbol, startup_symbol_to_point, startup_trace_to_complex_symbols
from .tx_passband import PassbandWaveform, baseband_to_passband
from .tx_waveform import BasebandWaveform, rrc_taps, symbols_to_baseband
from .training import (
    STATE_A,
    STATE_B,
    STATE_C,
    STATE_D,
    generate_conditioning_signal,
    generate_s_bar_segment,
    generate_s_segment,
    generate_trn_segment,
)
from .constellation import (
    V32_NONREDUNDANT_9600_CONSTELLATION,
    v32_nonredundant_symbol_to_point,
)
from .coding import (
    encode_v32_nr_symbol_bits,
    decode_v32_nr_symbol_index,
)
from .v32_rate_signal import (
    V32_CAP_4800,
    V32_CAP_9600,
    V32_CAP_TRELLIS,
    V32_CAP_CLEARDOWN,
    V32_RATE_SYNC_BITS,
    V32_E_SYNC_BITS,
    v32_rate_signal_bits,
    v32_e_sequence_bits,
    is_v32_rate_signal_bits,
    is_v32_e_sequence_bits,
    decode_v32_rate_signal,
    decode_v32_e_sequence,
    encode_v32_rate_sequence_bits,
    decode_v32_rate_sequence_symbols,
    v32_cap_mask,
    v32_highest_common_rate,
)
from .v32_startup import (
    generate_aa_segment,
    generate_cc_segment,
    generate_ac_segment,
    generate_ca_segment,
    generate_v32_call_startup_trace,
    generate_v32_answer_startup_trace,
)
from .v32_receiver import (
    V32DetectedEvent,
    V32LogicalReceiver,
)
from .data_mode import (
    SUPPORTED_DATA_RATES,
    DataModeEncoder,
    DataModeDecoder,
    encode_data_bits,
    decode_data_symbols_hard,
    decode_data_symbols_soft,
    encode_data_bytes,
)

__all__ = [
    "SUPPORTED_BIT_RATES",
    "bits_per_symbol",
    "encode_symbol_bits",
    "differential_encode",
    "convolution_encode",
    "EncoderState",
    "EncodedSymbol",
    "symbol_to_point",
    "RATE_14400",
    "RATE_12000",
    "RATE_9600",
    "RATE_7200",
    "RATE_4800",
    "SUPPORTED_RATE_MASK",
    "rate_mask_from_list",
    "list_from_rate_mask",
    "rate_signal_bits",
    "e_sequence_bits",
    "encode_rate_sequence_bits",
    "detect_s_sequence",
    "validate_rate_signal_bits",
    "validate_e_sequence_bits",
    "decode_rate_mask",
    "decode_e_rate",
    "detect_repeated_rate_signal",
    "highest_common_rate",
    "negotiate_startup_rate",
    "negotiate_renegotiation_rate",
    "DetectedEvent",
    "ReceiverStats",
    "V32bisLogicalReceiver",
    "TRN_INITIAL_SCRAMBLER_REGISTER",
    "RENEGOTIATION_INITIAL_SCRAMBLER_REGISTER",
    "POST_E_INITIAL_CONVOLUTION_STATE",
    "NORMAL_STARTUP_SCRAMBLER_RESET_AFTER_E",
    "startup_diff_state_from_final_trn_symbol",
    "startup_scrambler_register_from_trn",
    "RecoveredSymbol",
    "TimingSearchResult",
    "CarrierSearchResult",
    "JointSearchResult",
    "passband_to_baseband",
    "matched_filter",
    "ideal_symbol_samples",
    "nearest_symbol_label",
    "recover_symbols_with_frontend",
    "recover_symbols_ideal",
    "recover_symbols_with_timing_offset",
    "search_carrier_frequency",
    "search_timing_and_carrier",
    "search_symbol_timing",
    "symbol_error_metric",
    "ObservableSymbol",
    "flatten_startup_trace",
    "impair_stream",
    "impair_stream_burst",
    "impair_stream_insert",
    "impair_stream_q_neighbor",
    "impair_stream_random",
    "Scrambler",
    "Descrambler",
    "scrambler_tap",
    "STATE_A",
    "STATE_B",
    "STATE_C",
    "STATE_D",
    "generate_s_segment",
    "generate_s_bar_segment",
    "generate_trn_segment",
    "generate_conditioning_signal",
    "generate_call_startup_trace",
    "generate_answer_startup_trace",
    "SUPPORTED_DATA_RATES",
    "DataModeEncoder",
    "DataModeDecoder",
    "encode_data_bits",
    "decode_data_symbols_hard",
    "decode_data_symbols_soft",
    "encode_data_bytes",
    "TransmittedSymbol",
    "startup_symbol_to_point",
    "startup_trace_to_complex_symbols",
    "BasebandWaveform",
    "PassbandWaveform",
    "rrc_taps",
    "symbols_to_baseband",
    "baseband_to_passband",
    "simulate_startup",
    # V.32 non-redundant 9600 constellation
    "V32_NONREDUNDANT_9600_CONSTELLATION",
    "v32_nonredundant_symbol_to_point",
    # V.32 non-redundant 9600 encoder / decoder
    "encode_v32_nr_symbol_bits",
    "decode_v32_nr_symbol_index",
    # V.32 rate / E sequence helpers
    "V32_CAP_4800",
    "V32_CAP_9600",
    "V32_CAP_TRELLIS",
    "V32_CAP_CLEARDOWN",
    "V32_RATE_SYNC_BITS",
    "V32_E_SYNC_BITS",
    "v32_rate_signal_bits",
    "v32_e_sequence_bits",
    "is_v32_rate_signal_bits",
    "is_v32_e_sequence_bits",
    "decode_v32_rate_signal",
    "decode_v32_e_sequence",
    "encode_v32_rate_sequence_bits",
    "decode_v32_rate_sequence_symbols",
    "v32_cap_mask",
    "v32_highest_common_rate",
    # V.32 startup trace generators and segment factories
    "generate_aa_segment",
    "generate_cc_segment",
    "generate_ac_segment",
    "generate_ca_segment",
    "generate_v32_call_startup_trace",
    "generate_v32_answer_startup_trace",
    # V.32 logical receiver
    "V32DetectedEvent",
    "V32LogicalReceiver",
]
