#!/usr/bin/env python3
"""Emit golden H.245 PER vectors for representative V.75 messages.

  golden.py <h245.asn> > v75_h245_golden.h

The vectors come from asn1tools, an independent X.691 implementation, so
v75_test can check the typed encoder in C against bytes it did not produce
(and make test needs no Python).  The values here are mirrored in v75_test.c.
"""
import sys
import asn1tools

spec = asn1tools.compile_files(sys.argv[1], 'per')
T = 'MultimediaSystemControlMessage'


def v76(crc, n401, sr, mode, ah):
    return {'hdlcParameters': {'crcLength': (crc, None), 'n401': n401, 'loopbackTestProcedure': False},
            'suspendResume': (sr, None), 'uIH': False, 'mode': mode,
            'v75Parameters': {'audioHeaderPresent': ah}}


ERM = ('eRM', {'windowSize': 15, 'recovery': ('rej', None)})
UNERM = ('uNERM', None)
OID = '0.0.8.245.0.1'


def audio(): return ('audioData', ('g729AnnexA', 1))


def data(): return ('data', {'application': ('userData', ('v42lapm', None)), 'maxBitRate': 0})


M = {}
M['tcs'] = ('request', ('terminalCapabilitySet', {
    'sequenceNumber': 0, 'protocolIdentifier': OID,
    'multiplexCapability': ('v76Capability', {
        'suspendResumeCapabilitywAddress': False, 'suspendResumeCapabilitywoAddress': True,
        'rejCapability': True, 'sREJCapability': True, 'mREJCapability': False,
        'crc8bitCapability': True, 'crc16bitCapability': True, 'crc32bitCapability': False,
        'uihCapability': False, 'numOfDLCS': 4, 'twoOctetAddressFieldCapability': False,
        'loopBackTestCapability': False, 'n401Capability': 128, 'maxWindowSizeCapability': 15,
        'v75Capability': {'audioHeader': True}}),
    'capabilityTable': [
        {'capabilityTableEntryNumber': 1,
         'capability': ('receiveAndTransmitAudioCapability', ('g729AnnexA', 1))},
        {'capabilityTableEntryNumber': 2,
         'capability': ('receiveAndTransmitDataApplicationCapability',
                        {'application': ('userData', ('v42lapm', None)), 'maxBitRate': 0})}],
    'capabilityDescriptors': [{'capabilityDescriptorNumber': 0,
                               'simultaneousCapabilities': [[1], [2]]}]}))
M['olc_audio'] = ('request', ('openLogicalChannel', {
    'forwardLogicalChannelNumber': 3,
    'forwardLogicalChannelParameters': {
        'portNumber': 0, 'dataType': audio(),
        'multiplexParameters': ('v76LogicalChannelParameters',
                                v76('crc8bit', 12, 'suspendResumewoAddress', UNERM, True))},
    'reverseLogicalChannelParameters': {
        'dataType': audio(),
        'multiplexParameters': ('v76LogicalChannelParameters',
                                v76('crc8bit', 12, 'suspendResumewoAddress', UNERM, True))}}))
M['olc_data'] = ('request', ('openLogicalChannel', {
    'forwardLogicalChannelNumber': 4,
    'forwardLogicalChannelParameters': {
        'dataType': data(),
        'multiplexParameters': ('v76LogicalChannelParameters',
                                v76('crc16bit', 128, 'noSuspendResume', ERM, False))},
    'reverseLogicalChannelParameters': {
        'dataType': data(),
        'multiplexParameters': ('v76LogicalChannelParameters',
                                v76('crc16bit', 128, 'noSuspendResume', ERM, False))}}))
M['olc_ack'] = ('response', ('openLogicalChannelAck', {
    'forwardLogicalChannelNumber': 3,
    'reverseLogicalChannelParameters': {'reverseLogicalChannelNumber': 3, 'portNumber': 0}}))
M['olc_reject'] = ('response', ('openLogicalChannelReject', {
    'forwardLogicalChannelNumber': 9, 'cause': ('dataTypeNotSupported', None)}))
M['clc'] = ('request', ('closeLogicalChannel', {
    'forwardLogicalChannelNumber': 4, 'source': ('user', None)}))
M['clc_ack'] = ('response', ('closeLogicalChannelAck', {'forwardLogicalChannelNumber': 4}))
M['end_disconnect'] = ('command', ('endSessionCommand', ('disconnect', None)))
M['end_v34dsvd'] = ('command', ('endSessionCommand', ('gstnOptions', ('v34DSVD', None))))
M['tcs_ack'] = ('response', ('terminalCapabilitySetAck', {'sequenceNumber': 0}))
M['tcs_reject'] = ('response', ('terminalCapabilitySetReject', {
    'sequenceNumber': 0, 'cause': ('undefinedTableEntryUsed', None)}))
M['request_mode'] = ('request', ('requestMode', {
    'sequenceNumber': 5,
    'requestedModes': [[{'type': ('audioMode', ('g729AnnexA', None)),
                         'v76ModeParameters': ('suspendResumewoAddress', None)}]]}))
M['request_mode_ack'] = ('response', ('requestModeAck', {
    'sequenceNumber': 5, 'response': ('willTransmitMostPreferredMode', None)}))

print('/* GENERATED by tools/h245/golden.py from asn1tools: H.245 PER bytes the C encoder')
print(' * did not produce.  Mirrored by v75_test.c. */')
print('static const struct { const char *name; int len; uint8_t b[160]; } h245_golden[] = {')
for k, v in M.items():
    b = spec.encode(T, v)
    print('    { "%s", %d, { %s } },' % (k, len(b), ', '.join('0x%02x' % x for x in b)))
print('};')
