#!/usr/bin/env python3
"""Generate k56flex_tables.h and k56flex_firmware_vectors.h.

Usage: generate_k56flex_vectors.py <MicaEmu repo> <out dir>

Runs the original MICA C53 mapper (module 8C: D604 setup, D689 mapper, D744
bit partition, 490E shell unranking, BE68 scrambler) in the isolated
repeat-fetch core built by MicaEmu/tools/build_k56flex_core.py, and records
what it did.  Nothing here copies firmware program words; the tables are the
shipped level payloads (fixed data, K56flex Draft 0.23 clause 7.5) and the
vectors are firmware outputs for supplied inputs.
"""
import json, random, struct, sys
from bisect import bisect_right
from pathlib import Path

root = Path(sys.argv[1]).resolve()
out = Path(sys.argv[2]).resolve()
P = root / 'artifacts' / 'k56flex-recovery-20261004'
CORE = root / '.build' / 'k56flex-core'

sys.path.insert(0, str(CORE / 'python'))
import courier_emu.dsp as dsp  # noqa: E402
dsp.build_library = lambda **kw: CORE / 'libcourier_c5x.dylib'
c = dsp.NativeC5x.from_program(0, (P / 'flex.prog').read_bytes(), model='c53')
c.load_program((P / 'overlay-88.bin').read_bytes(), 0x4000)
c.load_program((P / 'overlay-8c.bin').read_bytes(), 0xd600)


def patch(addr, words):
    c.load_program(struct.pack('<' + 'H' * len(words), *words), addr)


def run(entry, acc=0, ar4=0, hook=None, limit=400000):
    words = [0xbc00, 0xbe47, 0xbe42, 0xbe4a, 0xbf09, 0x6800, 0xbf0a, 0x6400, 0xbf0c, ar4, 0x8b89,
             0xbf80, acc, 0x7a89, entry, 0x8b00]
    patch(0x7000, words)
    c.set_pc(0x7000)
    for _ in range(limit):
        pc = c.state()['pc']
        if pc == 0x700f:
            return
        if hook:
            hook(pc)
        c.step(1)
    raise AssertionError(c.state())


def counts(n, k):
    a = [1]
    for _ in range(k):
        b = [0] * (len(a) + n)
        for i, v in enumerate(a):
            for j in range(n + 1):
                b[i + j] += v
        a = b
    return a


def unrank(n, k, s, r, table):
    if k == 2:
        first = max(0, s - n) + r
        return [first, s - first]
    h = k // 2
    ct = table[h]
    for a in range(max(0, s - h * n), min(h * n, s) + 1):
        size = ct[a] * ct[s - a]
        if r < size:
            return unrank(n, h, a, r % ct[a], table) + unrank(n, h, s - a, r // ct[a], table)
        r -= size
    raise AssertionError((n, k, s, r))


def split_bits(word, width, pattern, signs):
    extras = []
    selectors = []
    consumed = 0
    if word & 0x80000000:
        word -= 1 << 32
    for sign in signs:
        stolen = pattern & 1
        pattern = (pattern >> 1) | (0x20 if stolen else 0)
        usable = width - stolen
        chunk = word >> consumed
        selectors.append((chunk & 1) if sign else 2)
        extras.append(((chunk >> sign) & ((1 << usable) - 1)) << stolen)
        consumed += usable + sign
    return extras, selectors, pattern, consumed


flash = (root / 'mica-portware-map.bin').read_bytes()
base = 0xe0010
patch(0x2d37, [0xef00])


def load_table(law, field, rate):
    flags = field & 0xc0
    index = rate + 52 * law + (15 if flags & 0x40 else 0) + (28 if flags & 0x80 else 0)
    off, size = struct.unpack_from('<HH', flash, base + 4 * index)
    payload = list(struct.unpack_from('<' + 'H' * size, flash, base + 2 * off))

    def loader(pc):
        if pc == 0x2d37:
            for i, v in enumerate(payload):
                c.set_data(0xe5e6 + i, v)
    c.set_data(0xec6e, law)
    c.set_data(0x8fef, field)
    c.set_data(0x8f2f, rate)
    run(0xd604, hook=loader)
    return index, payload


# ---------------------------------------------------------------- tables
tables = []
pool = []
for law in (0, 1):
    for flags in (0, 0x40, 0x80):
        for rate in range(19, 34 if flags == 0 else 32):
            index, payload = load_table(law, flags, rate)
            levels = [v - 65536 if v >= 32768 else v for v in payload[31:]]
            tables.append(dict(
                law=law, flags=flags, rate=rate, index=index,
                alloc=[c.data(0x8fd3 + j) for j in range(4)],
                pattern=[c.data(0xe66d + j) for j in range(16)],
                alphabet=c.data(0x8fd8),
                remap=payload[:16], first=len(pool), count=len(levels)))
            assert c.data(0x8fd8) == payload[16 + rate - 19]
            pool.extend(levels)

with (out / 'k56flex_tables.h').open('w') as f:
    f.write('/* Generated by tools/generate_k56flex_vectors.py.  Shipped K56flex level payloads\n'
            ' * (Draft 0.23 clause 7.5) and the per-rate allocation / sign-pattern records that\n'
            ' * the original D604 setup derives from them.  Do not edit. */\n')
    f.write('#ifndef K56FLEX_TABLES_H\n#define K56FLEX_TABLES_H\n\n#include <stdint.h>\n\n')
    f.write('typedef struct {\n    uint8_t law;           /* DM EC6E bit 0 */\n'
            '    uint8_t flags;         /* DM 8FEF bits 6/7 */\n'
            '    uint8_t rate_index;    /* MICA index 19..33 */\n'
            '    uint8_t alloc[4];      /* total bits, selector, amplitude bits, extra width */\n'
            '    uint8_t alphabet;      /* shell alphabet size */\n'
            '    uint8_t remap[16];\n    uint16_t sign_pattern;  /* E66D bits, phase 0 then 1 */\n'
            '    uint16_t first_level;\n    uint16_t level_count;\n} k56flex_table_t;\n\n')
    f.write('#define K56FLEX_TABLE_COUNT %d\n\n' % len(tables))
    f.write('static const int16_t k56flex_levels[%d] = {\n' % len(pool))
    for i in range(0, len(pool), 12):
        f.write('    ' + ', '.join(str(v) for v in pool[i:i + 12]) + ',\n')
    f.write('};\n\nstatic const k56flex_table_t k56flex_tables[K56FLEX_TABLE_COUNT] = {\n')
    for t in tables:
        sp = sum(b << i for i, b in enumerate(t['pattern']))
        assert all(b in (0, 1) for b in t['pattern'])
        f.write('    {%d, 0x%02x, %d, {%s}, %d, {%s}, 0x%04x, %d, %d},\n' % (
            t['law'], t['flags'], t['rate'], ', '.join(map(str, t['alloc'])), t['alphabet'],
            ', '.join(str(v) for v in t['remap']), sp, t['first'], t['count']))
    f.write('};\n\n#endif\n')

# --------------------------------------------------------------- vectors
rng = random.Random(5608)
fields_unadjusted = [0]
masks = [0x01, 0x03, 0x15, 0x2b, 0x0f]
fields_impaired = [0] + [(m.bit_count() << 9) | m for m in masks] + [(6 << 9) | 63]
runs = []


def one_run(law, rate, field, nframes):
    index, payload = load_table(law, field, rate)
    total, selector, amplitude_budget, width = [c.data(0x8fd3 + i) for i in range(4)]
    n = c.data(0x8fd8) - 1
    table = {k: counts(n, k) for k in (2, 4, 8)}
    cum = [0]
    for v in table[8]:
        cum.append(cum[-1] + v)
    c.set_data(0x8edf, 0xd380)
    run(0xb4ec)
    c.set_data(0x8c00, 0)
    c.set_data(0x8c21, 0xbe68)
    c.set_data(0x8f9d, 0)
    c.set_data(0x8f9e, 0)
    raw, scrambled, history = [], [], [0] * 23
    offset = 0
    dc = 0
    phase = 0
    mask = c.data(0x8ff5)
    impairment = (field >> 9) & 7
    samples = []

    def append_word(word, first=False):
        raw.append(word)
        for i in range(16):
            y = ((word >> i) & 1) ^ history[-5] ^ history[-23]
            history.append(y)
            scrambled.append(y)
        run(0x90bd if first else 0x90d0, acc=word)

    append_word(rng.randrange(65536), True)
    pattern = [c.data(0xe66d + i) for i in range(16)]
    for frame in range(nframes):
        while c.data(0x8c5a) < 6:
            append_word(rng.randrange(65536))
        phase = int(bool(selector & 4) and phase == 0)
        budget = amplitude_budget - phase
        loss = 0
        shift = 0
        if rate > 20 and impairment:
            loss = impairment + ((field >> (2 * (frame % 3))) & 3).bit_count()
            if impairment == 1:
                shift = 0 if loss == 2 else 1
            elif impairment == 2:
                shift = 0 if loss == 4 else (2 if loss == 2 else 1)
            elif impairment == 4:
                shift = 0 if loss == 6 else (2 if loss == 4 else 1)
        if rate <= 20:
            mask = 0
        request = budget - shift
        rank = sum(scrambled[offset + i] << i for i in range(request)) << shift
        offset += request
        shell = bisect_right(cum, rank) - 1
        amplitudes = unrank(n, 8, shell, rank - cum[shell], table)
        remaining = total - budget - loss
        extra_word = sum(scrambled[offset + i] << i for i in range(remaining))
        offset += remaining
        extras, signs, mask, consumed = split_bits(extra_word, width, mask,
                                                   pattern[8 * phase:8 * phase + 8])
        assert consumed == remaining, (law, rate, field, frame)
        expected = []
        for a, e, s in zip(amplitudes, extras, signs):
            level = payload[31 + (payload[a] << width | e)]
            if level >= 32768:
                level -= 65536
            if s == 1 or (s == 2 and dc >= 0):
                level = -level
            dc += level
            expected.append(level)
        run(0xd689)
        actual = [c.data(0x8f80 + i) for i in range(8)]
        actual = [v - 65536 if v >= 32768 else v for v in actual]
        assert actual == expected, (law, rate, field, frame, actual, expected)
        assert c.data(0x8ff5) == mask
        samples += actual
    runs.append(dict(law=law, rate=rate, field=field, frames=nframes, words=raw, samples=samples))


for law in (0, 1):
    for rate in range(19, 32):
        one_run(law, rate, 0, 24)
    for rate in (21, 26, 31):
        for field in fields_impaired[1:]:
            one_run(law, rate, field, 9)
    # rate 19/20 ignore any report; confirm that against the firmware too.
    for rate in (19, 20):
        one_run(law, rate, fields_impaired[1], 6)

# Table 7/8 selector flags (bits 6/7): firmware level tables for the adjusted groups.
for law in (0, 1):
    for flags in (0x40, 0x80):
        for rate in (22, 31):
            one_run(law, rate, flags, 12)
            one_run(law, rate, flags | (2 << 9) | 0x03, 9)  # selector == popcount, as 1521 builds it

# ----------------------------------------------- parameter record (4.12)
# Bank 88 entry 4269 builds the record; 90BD/90DC queue it as DA56 does.
param_runs = []
prng = random.Random(5605)
for case in range(48):
    mode = case % 2
    v = dict(extra=prng.randrange(16), rate=prng.randrange(1, 16), suppress=prng.randrange(2),
             u=prng.randrange(2), v=prng.randrange(2), control=prng.randrange(0x8000),
             bit=prng.randrange(2), special=prng.randrange(2), final=prng.randrange(2))
    if case % 8 == 7:
        v['special'] = 1
    for a, w in {0x8c76: mode, 0x8c77: v['extra'], 0x8c78: v['rate'],
                 0x8f4f: 0x10 * v['suppress'], 0x8fd0: v['u'], 0x8fd1: v['v'],
                 0x8fba: v['control'], 0x8fbc: v['bit'], 0x8faa: v['special']}.items():
        c.set_data(a, w)
    run(0x4269, acc=v['final'])
    run(0x90bd, acc=65535)
    c.set_data(0x67ff, 192 if mode else 96)
    queued = []
    run(0x90dc, ar4=0xdb1a,
        hook=lambda pc: queued.append(c.state()['acc'] & 65535) if pc == 0x90d0 else None)
    param_runs.append(dict(mode=mode, queued=queued, **v))

with (out / 'k56flex_firmware_vectors.h').open('w') as f:
    f.write('/* Generated by tools/generate_k56flex_vectors.py from original MICA C53 module 8C\n'
            ' * (D604/D689/D744/490E/BE68) executed in the isolated repeat-fetch core.  Inputs are\n'
            ' * supplied source words; outputs are signed level words (not G.711 octets).  Do not\n'
            ' * edit. */\n#ifndef K56FLEX_FIRMWARE_VECTORS_H\n#define K56FLEX_FIRMWARE_VECTORS_H\n\n'
            '#include <stdint.h>\n\n')
    words_pool, sample_pool = [], []
    for r in runs:
        r['w0'] = len(words_pool)
        words_pool += r['words']
        r['s0'] = len(sample_pool)
        sample_pool += r['samples']
    f.write('typedef struct {\n    uint8_t law;\n    uint8_t rate_index;\n    uint16_t field;\n'
            '    uint16_t frames;\n    uint16_t nwords;\n    uint32_t word_offset;\n'
            '    uint32_t sample_offset;\n} k56flex_vector_t;\n\n')
    f.write('#define K56FLEX_VECTOR_COUNT %d\n\n' % len(runs))
    f.write('static const uint16_t k56flex_vector_words[%d] = {\n' % len(words_pool))
    for i in range(0, len(words_pool), 12):
        f.write('    ' + ', '.join('0x%04x' % v for v in words_pool[i:i + 12]) + ',\n')
    f.write('};\n\nstatic const int16_t k56flex_vector_samples[%d] = {\n' % len(sample_pool))
    for i in range(0, len(sample_pool), 16):
        f.write('    ' + ', '.join(str(v) for v in sample_pool[i:i + 16]) + ',\n')
    f.write('};\n\nstatic const k56flex_vector_t k56flex_vectors[K56FLEX_VECTOR_COUNT] = {\n')
    for r in runs:
        f.write('    {%d, %d, 0x%04x, %d, %d, %d, %d},\n' % (
            r['law'], r['rate'], r['field'], r['frames'], len(r['words']), r['w0'], r['s0']))
    f.write('};\n\n')
    f.write('typedef struct {\n    uint8_t mode, extra, rate, suppress_extra, u, v, bit, special, final;\n'
            '    uint16_t control;\n    uint16_t queued[12];\n} k56flex_param_vector_t;\n\n')
    f.write('#define K56FLEX_PARAM_VECTOR_COUNT %d\n\n' % len(param_runs))
    f.write('static const k56flex_param_vector_t k56flex_param_vectors[K56FLEX_PARAM_VECTOR_COUNT] = {\n')
    for r in param_runs:
        q = r['queued'] + [0] * (12 - len(r['queued']))
        f.write('    {%d, %d, %d, %d, %d, %d, %d, %d, %d, 0x%04x, {%s}},\n' % (
            r['mode'], r['extra'], r['rate'], r['suppress'], r['u'], r['v'], r['bit'],
            r['special'], r['final'], r['control'], ', '.join('0x%04x' % w for w in q)))
    f.write('};\n\n#endif\n')

print('tables', len(tables), 'levels', len(pool), 'runs', len(runs),
      'frames', sum(r['frames'] for r in runs))
