"""Run original QF060003 instructions to generate portable x2 regression vectors.
Run with courier-emu's .venv Python; first argument is courier-emu root,
second is the destination x2_firmware_vectors.h. No firmware is embedded.
"""
import sys, random
from pathlib import Path
sys.path.insert(0, sys.argv[1])
from tools.recover_x2_payload import Runner
rng = random.Random(0xc5df)
configs=[]; cases=[]
for rate in range(1,16):
 for flag in (0,1):
  r=Runner()
  r.put({0x340:0,0xe8f1:0,0xe8f2:0x600,0xffd9:flag,0x3fb:1,0x39f:64})
  r.run(0xc862,acc=rate,spm=1)
  B=r.core.data(0x3c0)
  sizes=[r.core.data(0x4bb-i) for i in range(6)]
  banks=[[r.core.data(0xe8f4+128*i+j) for j in range(size)] for i,size in enumerate(sizes)]
  levels=[r.core.data(0xed4f+i) for i in range(128)]
  levels=[x if x<32768 else x-65536 for x in levels]
  configs.append((B,sizes,banks,levels))
  for case in range(28):
   md=case%7; parity=rng.randrange(2); monitor=rng.randrange(-32768,32768)
   payload=rng.getrandbits(B+md); fmt=0x2a if case&1 else 0
   r.put({0x3ed:md,0x3af:0,0x3da:parity<<15,0x39f:64,0x4d2:monitor&65535,
          **{0x248+i:(payload>>(16*i))&65535 for i in range(8)}})
   r.run(0xc5df);r.run(0xc642)
   octets=[(r.core.data(0x4c1-i)&255)^fmt for i in range(6)]
   cases.append((len(configs)-1,md,fmt,parity,monitor,payload,octets,r.core.data(0x3da)>>15))
  r.core.close()
def arr(xs):return '{'+','.join(map(str,xs))+'}'
out=['/* Generated by original QF060003 C862 (SPM=1), C5DF, C642.\n * Seed 0xc5df; 30 seeded profiles, 840 original-instruction contexts.\n * Configurations are constructed test profiles, not captured negotiations. */',
     'static const x2_pcm_config_t firmware_profiles[] = {']
for B,sizes,banks,levels in configs:
 out.append('{'+f'{B},0,0,'+arr(sizes)+','+'{'+','.join(arr(b) for b in banks)+'},'+arr(levels)+'},')
out+=['};','struct firmware_case { unsigned profile, md, format, parity; int16_t monitor; uint64_t payload; uint8_t octets[6], final_parity; };','static const struct firmware_case firmware_cases[] = {']
for p,md,fmt,parity,mon,bits,octets,end in cases:
 out.append('{'+f'{p},{md},{fmt},{parity},{mon},UINT64_C({bits}),'+arr(octets)+f',{end}'+'},')
out+=['};','']
out += ['struct firmware_stream { unsigned profile, md, tap, format, source_count; uint8_t source[256], octets[192]; };', 'static const struct firmware_stream firmware_streams[] = {']
for rate in (10,15):
 for role in (0,1):
  for flag in (0,1):
   for md in range(7):
    r=Runner();r.put({0x340:0,0xe8f1:0,0xe8f2:0x600,0xffd9:flag,0x3fb:1,0x39f:64});r.run(0xc862,acc=rate,spm=1)
    fmt=0x2a if flag else 0
    r.put({0x6f:role,0x3ed:md,0x3af:0,0x3ae:0,0x3da:0,0x3fb:1,0x39f:64,0x3cc:5,0x3f4:5,0x3ca:6,0x3cb:0xc64b,0x3de:0,0x3df:0,0x3c5:0,0x3c6:0,0xffd9:flag,0xe8e4:0,0x3d8:0,0x3d9:0,0x3d1:255,0x3d2:8,0x3a3:fmt,
           **{a:0 for a in range(0x4ce,0x4d4)},**{a:0 for a in range(0x248,0x250)}})
    source=[];octets=[];count=r.core.data(0x3c0)+md
    for frame in range(32):
     while ((r.core.data(0x3ae)-r.core.data(0x3af))&127)<=2*count:
      byte=rng.randrange(256);source.append(byte);r.put({0x3d0:byte});r.run(0xb2ba)
     if r.core.data(0x3ca)==0:r.put({0x3ca:6})
     for i in range(6):r.run(0xc544,spm=1);octets.append(r.core.data(0x3a7))
    assert len(source)<=256
    out.append('{'+f'{(rate-1)*2+flag},{md},{5 if role else 18},{fmt},{len(source)},'+arr(source)+','+arr(octets)+'},')
    r.core.close()
out+=['};','']
Path(sys.argv[2]).write_text('\n'.join(out))
print(f'Generated {len(cases)} original DSP vectors from {len(configs)} profiles')
