#!/usr/bin/env python3
"""Export original I-modem symmetric source/history captures, no program words.
Usage: python3 tools/generate_x2_sym_vectors.py <x2-xc-pair-20261004> <output.h>
"""
import hashlib
import json
import sys
from pathlib import Path

folder, output = map(Path, sys.argv[1:])
rows, hashes = [], []
for side in ('originate', 'answer'):
    path = folder / f'{side}.json'
    raw = path.read_bytes()
    hashes.append(f'{side}: {hashlib.sha256(raw).hexdigest()}')
    result = json.loads(raw)
    selected = []
    for group in result['digital_path_trace']['samples']:
        if group['phase'] != 'transmit':
            continue
        for a, b in zip(group['captures'], group['captures'][1:]):
            assert a[6:8] == [255, 8] and a[10] & 0x200 and a[13] & 0x8000
            assert a[14:18] == [0xe97e, 0xe992, 0xe97e, 0xe992]
            assert b[0] > a[0]
            selected.append((a[5], (a[8] << 16) | a[9], (b[8] << 16) | b[9]))
            if len(selected) == 64:
                break
        if len(selected) == 64:
            break
    assert len(selected) == 64
    rows.extend(selected)
with output.open('w') as f:
    f.write('/* Original Ie030002 E97E source/history transitions, 64 per role.\n')
    f.write(' * Generated by tools/generate_x2_sym_vectors.py from x2-xc-pair-20261004.\n')
    for item in hashes:
        f.write(f' * {item}\n')
    f.write(' * No firmware words. */\n')
    f.write('static const struct { unsigned source, before, after; } sym_vectors[] = {\n')
    for a, b, c in rows:
        f.write(f'    {{0x{a:02x},0x{b:06x},0x{c:06x}}},\n')
    f.write('};\n')
