#!/usr/bin/env python3
"""Generate k56flex_probe_tables.h and k56flex_probe_vectors.h.

Usage: generate_k56flex_probe_vectors.py <MicaEmu repo> <out dir> [courier-emu repo]

Runs the original MICA C53 module 8C probe sample generator (D811 configuration
load, D873 block: 90FF source fetch, D890 sequence selection, D83C level lookup,
D84F sign/DC adjustment) in the stock courier-emu core, for each training
stage, both laws and the three pad-table groups.  Tables are the shipped
configuration words and level lists D811 selects; vectors are firmware outputs
for supplied source words.  Clause 4.10 of K56flex Draft 0.23.
"""
import random, struct, sys
from pathlib import Path

root = Path(sys.argv[1]).resolve()
out = Path(sys.argv[2]).resolve()
P = root / 'artifacts' / 'k56flex-recovery-20261004'
# The stock courier-emu core, not the isolated repeat-fetch core: the patched core
# mishandles RPT inside RPTB (D83C's level loop writes only three of six samples
# there).  The patch exists for B57E/490E and is only validated for the mapper.
COURIER = Path(sys.argv[3] if len(sys.argv) > 3 else root.parent / 'courier-emu').resolve()
sys.path.insert(0, str(COURIER))
import courier_emu.dsp as dsp  # noqa: E402
dsp.build_library = lambda **kw: COURIER / '.build' / 'libcourier_c5x.dylib'
c = dsp.NativeC5x.from_program(0, (P / 'flex.prog').read_bytes(), model='c53')
c.load_program((P / 'overlay-8c.bin').read_bytes(), 0xd600)
c.load_program((P / 'overlay-88.bin').read_bytes(), 0x4000)


def patch(addr, words):
    c.load_program(struct.pack('<' + 'H' * len(words), *words), addr)


def run(entry, acc=0, hook=None, limit=400000):
    words = [0xbc00, 0xbe47, 0xbe42, 0xbe4a, 0xbf09, 0x6800, 0xbf0a, 0x6400, 0xbf0c, 0, 0x8b89,
             0xbf80, acc, 0x7a89, entry, 0x8b00]
    patch(0x7000, words)
    c.set_pc(0x7000)
    for _ in range(limit):
        if c.state()['pc'] == 0x700f:
            return
        c.step(1)
    raise AssertionError(c.state())


STAGES = [('SIL', 0xd9be), ('ID', 0xd960), ('P1', 0xd971), ('P2', 0xd97e),
          ('P3', 0xd98b), ('PA', 0xd99c), ('PB', 0xd9ad)]
for addr in (0xd7ef, 0x6582, 0x4f72):
    patch(addr, [0xef00])          # queue, receive service and yield bypassed

tables, pool, vectors, words_pool, samples_pool = [], [], [], [], []
rng = random.Random(4100)


def configure(stage_addr, law, flags):
    c.set_data(0xec6e, law)
    c.set_data(0x8fef, flags)
    c.set_data(0x8c00, 0)
    run(0xd811, acc=stage_addr)
    cfg = [c.data(0x8f90 + i) for i in range(12)]
    ptr = cfg[11]
    mask = cfg[9]
    levels = [c.program(ptr + j) for j in range(mask + 1)]
    return cfg, [v - 65536 if v >= 32768 else v for v in levels]


for si, (name, addr) in enumerate(STAGES):
    for law in (0, 1):
        for flags in (0, 0x40, 0x80):
            cfg, levels = configure(addr, law, flags)
            tables.append(dict(stage=si, law=law, flags=flags, cfg=cfg, first=len(pool), n=len(levels)))
            pool += levels
            # source modes: scrambled (BE68) and raw (8F6F)
            for mode in (('scr', 0xbe68), ('raw', 0x8f6f)):
                for seq0 in ((0, 0), (2, 0x800)):
                    cfg, _ = configure(addr, law, flags)
                    for a in (0x8f9d, 0x8f9e):
                        c.set_data(a, 0)
                    c.set_data(0x8f88, seq0[0])
                    c.set_data(0x8f89, seq0[1])
                    c.set_data(0x8c1f, cfg[3])
                    c.set_data(0x8c21, mode[1])
                    seed = rng.choice([0xffff, 0xe4e4, 0x1b1b, rng.randrange(65536)])
                    run(0x90bd, acc=seed)
                    extra = [rng.randrange(65536) for _ in range(rng.choice([0, 1, 3]))]
                    for w in extra:
                        run(0x90d0, acc=w)
                    nblocks = 48
                    samples = []
                    for _ in range(nblocks):
                        run(0xd873)
                        samples += [c.data(0x8f80 + j) for j in range(cfg[0])]
                    samples = [v - 65536 if v >= 32768 else v for v in samples]
                    vectors.append(dict(stage=si, law=law, flags=flags, scr=mode[0] == 'scr',
                                        seq=seq0, words=[seed] + extra, blocks=nblocks,
                                        per_block=cfg[0], samples=samples))

with (out / 'k56flex_probe_tables.h').open('w') as f:
    f.write('/* Generated by tools/generate_k56flex_probe_vectors.py.  Probe-stage configuration\n'
            ' * words (as D811 loads them into DM 8F90..8F9B) and level lists, Draft 0.23\n'
            ' * clause 4.10.  Do not edit. */\n#ifndef K56FLEX_PROBE_TABLES_H\n#define K56FLEX_PROBE_TABLES_H\n\n'
            '#include <stdint.h>\n\n')
    f.write('typedef struct {\n    uint8_t stage, law, flags;\n    uint16_t cfg[12];\n'
            '    uint16_t first_level, level_count;\n} k56flex_probe_table_t;\n\n')
    f.write('#define K56FLEX_PROBE_TABLE_COUNT %d\n\nstatic const int16_t k56flex_probe_levels[%d] = {\n'
            % (len(tables), len(pool)))
    for i in range(0, len(pool), 12):
        f.write('    ' + ', '.join(str(v) for v in pool[i:i + 12]) + ',\n')
    f.write('};\n\nstatic const k56flex_probe_table_t k56flex_probe_tables[K56FLEX_PROBE_TABLE_COUNT] = {\n')
    for t in tables:
        f.write('    {%d, %d, 0x%02x, {%s}, %d, %d},\n' % (
            t['stage'], t['law'], t['flags'], ', '.join('0x%04x' % v for v in t['cfg']), t['first'], t['n']))
    f.write('};\n\n#endif\n')

# ---------------------------------------------- composite training timeline
# The fixed stage order and pair counts of clauses 4.10/4.11, built from the same
# primitives DB11/DB2E/DB37/DB68/DB7F/D9CB call (D811, 90BD/90D0, D7D1 pairs).  The
# peer-gated stretches use a stand-in pair count.  Each segment is hashed (FNV-1a 64
# over little-endian int16 samples) so the whole stream stays checkable in a small file.
GATE = dict(A=40, B=10, C=20)
SEGMENTS = ['SIL0', 'ID_A', 'ID_B', 'P1', 'P2', 'P3', 'GATE_A', 'GATE_B', 'ID2_A', 'ID2_B',
            'PT_A', 'PT_B', 'PT_C', 'GATE_C']


def fnv(samples, h=0xcbf29ce484222325):
    for v in samples:
        for b in struct.pack('<h', v):
            h = ((h ^ b) * 0x100000001b3) & 0xffffffffffffffff
    return h


def timeline(law, flags, bit8):
    out = []
    state = {}

    def use(addr, scr):
        cfg, _ = configure(addr, law, flags | (0x100 if bit8 else 0))
        c.set_data(0x8c1f, cfg[3])
        c.set_data(0x8c21, 0xbe68 if scr else 0x8f6f)
        state['cfg'] = cfg

    def pairs(n):
        samples = []
        for _ in range(2 * n):
            run(0xd873)
            samples += [c.data(0x8f80 + j) for j in range(state['cfg'][0])]
        samples = [v - 65536 if v >= 32768 else v for v in samples]
        out.append(fnv(samples))

    def clear():
        for a in (0x8f9d, 0x8f9e, 0x8f88, 0x8f89):
            c.set_data(a, 0)

    def ident():
        use(0xd960, False)
        run(0x90bd, acc=0xe4e4)
        pairs(22)
        run(0x90d0, acc=0x1b1b)
        pairs(2)

    clear()
    use(0xd9be, True)
    run(0x90bd, acc=0xffff)
    pairs(47)                                           # SIL0
    ident()                                             # ID_A, ID_B
    clear()
    use(0xd971, True)
    run(0x90bd, acc=0xffff)
    pairs(1364)                                         # P1
    use(0xd97e, True)
    c.set_data(0x8f88, 2)
    c.set_data(0x8f89, 0x800)
    pairs(704)                                          # P2
    use(0xd98b, True)
    pairs(1366)                                         # P3
    run(0x90d0, acc=0xffff)
    pairs(GATE['A'])                                    # GATE_A
    use(0xd9be, True)
    pairs(GATE['B'])                                    # GATE_B
    ident()                                             # ID2_A, ID2_B
    clear()
    use(0xd98b, True)
    run(0x90bd, acc=0xffff)
    pairs(688)                                          # PT_A
    for w in (0xffff, 0xffff, 0x0000):
        run(0x90d0, acc=w)
    pairs(8)                                            # PT_B
    use(0xd9ad if bit8 else 0xd99c, True)
    run(0x90d0, acc=0xffff)
    pairs(340)                                          # PT_C
    pairs(GATE['C'])                                    # GATE_C
    return out


timelines = []
for law in (0, 1):
    for bit8 in (0, 1):
        timelines.append((law, bit8, timeline(law, 0, bit8)))

for v in vectors:
    v['w0'] = len(words_pool)
    words_pool += v['words']
    v['s0'] = len(samples_pool)
    samples_pool += v['samples']
with (out / 'k56flex_probe_vectors.h').open('w') as f:
    f.write('/* Generated by tools/generate_k56flex_probe_vectors.py from original MICA C53 module 8C\n'
            ' * (D873 and callees).  Do not edit. */\n#ifndef K56FLEX_PROBE_VECTORS_H\n'
            '#define K56FLEX_PROBE_VECTORS_H\n\n#include <stdint.h>\n\n')
    f.write('typedef struct {\n    uint8_t stage, law, flags, scrambled;\n    uint16_t seq_hi, seq_lo;\n'
            '    uint16_t nwords, blocks, per_block;\n    uint32_t word_offset, sample_offset;\n} k56flex_probe_vector_t;\n\n')
    f.write('#define K56FLEX_PROBE_VECTOR_COUNT %d\n\nstatic const uint16_t k56flex_probe_vector_words[%d] = {\n'
            % (len(vectors), len(words_pool)))
    for i in range(0, len(words_pool), 12):
        f.write('    ' + ', '.join('0x%04x' % v for v in words_pool[i:i + 12]) + ',\n')
    f.write('};\n\nstatic const int16_t k56flex_probe_vector_samples[%d] = {\n' % len(samples_pool))
    for i in range(0, len(samples_pool), 16):
        f.write('    ' + ', '.join(str(v) for v in samples_pool[i:i + 16]) + ',\n')
    f.write('};\n\nstatic const k56flex_probe_vector_t k56flex_probe_vectors[K56FLEX_PROBE_VECTOR_COUNT] = {\n')
    for v in vectors:
        f.write('    {%d, %d, 0x%02x, %d, 0x%04x, 0x%04x, %d, %d, %d, %d, %d},\n' % (
            v['stage'], v['law'], v['flags'], v['scr'], v['seq'][0], v['seq'][1], len(v['words']),
            v['blocks'], v['per_block'], v['w0'], v['s0']))
    f.write('};\n\n#endif\n')
with (out / 'k56flex_train_vectors.h').open('w') as f:
    f.write('/* Generated by tools/generate_k56flex_probe_vectors.py: per-segment FNV-1a hashes of the\n'
            ' * composite training stream produced by original module 8C primitives.  Do not edit. */\n'
            '#ifndef K56FLEX_TRAIN_VECTORS_H\n#define K56FLEX_TRAIN_VECTORS_H\n\n#include <stdint.h>\n\n')
    f.write('#define K56FLEX_TRAIN_SEGMENTS %d\n#define K56FLEX_TRAIN_GATE_A %d\n#define K56FLEX_TRAIN_GATE_B %d\n'
            '#define K56FLEX_TRAIN_GATE_C %d\n\n' % (len(SEGMENTS), GATE['A'], GATE['B'], GATE['C']))
    f.write('static const uint16_t k56flex_train_pairs[K56FLEX_TRAIN_SEGMENTS] = {47, 22, 2, 1364, 704, 1366, %d, %d, 22, 2, 688, 8, 340, %d};\n\n'
            % (GATE['A'], GATE['B'], GATE['C']))
    f.write('typedef struct { uint8_t law, bit8; uint64_t hash[K56FLEX_TRAIN_SEGMENTS]; } k56flex_train_vector_t;\n\n')
    f.write('static const k56flex_train_vector_t k56flex_train_vectors[%d] = {\n' % len(timelines))
    for law, bit8, hs in timelines:
        f.write('    {%d, %d, {%s}},\n' % (law, bit8, ', '.join('UINT64_C(0x%016x)' % h for h in hs)))
    f.write('};\n\n#endif\n')

print('tables', len(tables), 'levels', len(pool), 'vectors', len(vectors), 'samples', len(samples_pool))
