#!/usr/bin/env python3
"""Fit the V.92 upstream loop channel from a real call, for v92_line_channel.

Input:
- our own analogue upstream at 16 kHz (`v92_p3_rx_line_test --dump-tx`),
- the digital side's G.711 receive tap from a live call that carried the
  same signal: artifacts/v92-loop-upstream/live-rx.g711.

TRN1u is the anchor.  V.92 8.5.7 zero-initialises its scrambler, so ours and
the call's are the same symbols.

Model: received[n] = sum_k h[k] * ours16k[2n + d - k], an FIR at 16 kHz
followed by the network A/D taking every other sample.  The script searches
the alignment d and a clock offset (resampling ours), solves h by least
squares on the first two thirds of the window, and scores it on the last
third.  It writes the taps, normalised to unit gain at 1333 Hz (Ru's line),
as v92_line_channel_r4.h.  So the model carries the loop's SHAPE and leaves
the level to the harness.

  v92_fit_line_channel.py <ours16k.s16> <ours-trn1u-symbol> <live-rx.g711>
                          <rx-trn1u-sample> [--taps 64] [--len 1200]
                          [--out v92_line_channel_r4.h]

Needs numpy.
"""
import argparse
import numpy as np


def ulaw2lin(b):
    c = (~b.astype(np.int32)) & 0xFF
    s, e, m = c & 0x80, (c >> 4) & 7, c & 15
    v = (((m << 3) + 0x84) << e) - 0x84
    return np.where(s, -v, v).astype(float)


def resample(x, ppm):
    """x observed by a clock `ppm` fast: sample i is at time i/(1+ppm)."""
    if ppm == 0:
        return x
    t = np.arange(len(x)) / (1 + ppm * 1e-6)
    return np.interp(t, np.arange(len(x)), x)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("ours")
    ap.add_argument("ours_trn1u", type=int)
    ap.add_argument("rx")
    ap.add_argument("rx_trn1u", type=int)
    ap.add_argument("--taps", type=int, default=64)
    ap.add_argument("--len", type=int, default=1200)
    ap.add_argument("--skip", type=int, default=100)
    ap.add_argument("--out", default="v92_line_channel_r4.h")
    a = ap.parse_args()

    ours = np.fromfile(a.ours, dtype="<i2").astype(float)
    rx = ulaw2lin(np.fromfile(a.rx, dtype=np.uint8))
    nt, L, train = a.taps, a.len, a.len * 2 // 3
    n0 = a.rx_trn1u + a.skip
    base = 2 * (a.ours_trn1u + a.skip)
    y = rx[n0:n0 + L]
    best = None
    for ppm in range(-300, 301, 25):
        src = resample(ours, ppm)
        for d in range(-40, 41):
            idx = base + d + 2 * np.arange(L)
            A = np.stack([src[idx - k] for k in range(nt)], axis=1)
            h, *_ = np.linalg.lstsq(A[:train], y[:train], rcond=None)
            e = y[train:] - A[train:] @ h
            r2 = 1 - np.mean(e ** 2) / np.mean(y[train:] ** 2)
            if best is None or r2 > best[0]:
                best = (r2, ppm, d, h)
    r2, ppm, d, h = best
    snr = 10 * np.log10(r2 / (1 - r2))
    w = 2 * np.pi * 1333.333 / 16000
    g = abs(np.sum(h * np.exp(-1j * w * np.arange(nt))))
    hn = h / g
    print("best: ppm %+d  d %+d  held-out R2 %.4f  SNR %.1f dB  "
          "gain at 1333 Hz %.4g" % (ppm, d, r2, snr, g))
    resp = [abs(np.sum(hn * np.exp(-2j * np.pi * f / 16000 * np.arange(nt))))
            for f in (300, 1000, 2000, 3000, 3400, 3800)]
    print("normalised |H| at 300/1000/2000/3000/3400/3800 Hz: "
          + " ".join("%.2f" % v for v in resp))
    with open(a.out, "w") as f:
        f.write("/* Generated by tools/v92_fit_line_channel.py -- data, not code.\n"
                " * The r4 loop (artifacts/v92-loop-upstream): our 16 kHz upstream\n"
                " * to the network A/D, %d taps at 16 kHz, unit gain at 1333 Hz.\n"
                " * Fit: clock %+d ppm, alignment %+d, held-out R2 %.4f (%.1f dB).\n"
                " */\n" % (nt, ppm, d, r2, snr))
        f.write("#define V92_LINE_CHANNEL_R4_TAPS \\\n")
        for i in range(0, nt, 4):
            f.write("    " + ", ".join("%.9g" % v for v in hn[i:i + 4])
                    + (", \\\n" if i + 4 < nt else " \\\n"))
        f.write("\n")


if __name__ == "__main__":
    main()
